### PR TITLE
More stories

### PR DESCRIPTION
**Pull request by sidharthramesh**

### CODE REVIEW

**Comment by joostholslag** [comment]
I suggested some typo fixes. Because I like to support this project, and it's all I can think of as a way to contribute. I hope it's appreciated.

**Comment by sidharthramesh** [comment]
> I suggested some typo fixes. Because I like to support this project, and it's all I can think of as a way to contribute. I hope it's appreciated.

Of course!! It's very much appreciated!

**Comment by sidharthramesh** [comment]
@joostholslag where can I find your suggestions? Did you create an issue? I can't seem to find it.

**Comment by joostholslag** [comment]
> @joostholslag where can I find your suggestions? Did you create an issue? I can't seem to find it.

Can you see them now? https://github.com/sidharthramesh/medblocks-ui/pull/27#discussion_r632299948

**Comment by sidharthramesh** [comment]
> > @joostholslag where can I find your suggestions? Did you create an issue? I can't seem to find it.
> 
> Can you see them now? [#27 (comment)](https://github.com/sidharthramesh/medblocks-ui/pull/27#discussion_r632299948)

Thank you @joostholslag. I've applied your suggestions.

**Pull request merged**
